import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://staging-fe.talenzap.com/categories');
  await page.getByPlaceholder('Search').click();
  await page.getByPlaceholder('Search').fill('dance');
  await page.getByRole('link', { name: 'Dance123 Enabled Clarity is' }).click();
  await page.getByLabel('Go back').click();
  await page.getByRole('button', { name: 'Add a category' }).click();
  await page.getByPlaceholder('Enter category name').click();
  await page.getByPlaceholder('Enter category name').fill('Dance ');
  await page.getByPlaceholder('Enter a description').click();
  await page.getByPlaceholder('Enter a description').fill('Dance competition');
  await page.getByPlaceholder('Enter sub category name').click();
  await page.getByPlaceholder('Enter sub category name').fill('Hip-Hop');
  await page.getByPlaceholder('Enter sub category name').press('Enter');
  await page.getByRole('button', { name: 'Create category' }).click();
  await page.locator('div').filter({ hasText: /^DanceEnabledDance competition1 Sub categoriesEdit$/ }).getByRole('switch').click();
  await page.locator('div').filter({ hasText: /^DanceDisabledDance competition1 Sub categoriesEdit$/ }).getByRole('switch').click();
  await page.locator('div').filter({ hasText: /^DanceEnabledDance competition1 Sub categoriesEdit$/ }).getByRole('button').click();
  await page.getByPlaceholder('Enter category name').click();
  await page.getByPlaceholder('Enter category name').fill('Dance style');
  await page.getByRole('button', { name: 'Save changes' }).click();
  await page.locator('div').filter({ hasText: /^Dance styleEnabledDance competition1 Sub categoriesEdit$/ }).getByRole('button').click();
  await page.getByPlaceholder('Enter a description').click();
  await page.getByPlaceholder('Enter a description').fill('Dance competition2');
  await page.getByRole('button', { name: 'Save changes' }).click();
  await page.getByRole('button', { name: 'Close' }).click();
  await page.locator('div').filter({ hasText: /^Dance styleEnabledDance competition1 Sub categoriesEdit$/ }).getByRole('button').click();
  await page.getByRole('button', { name: 'Close' }).click();
  await page.getByRole('button', { name: 'Filter' }).click();
  await page.getByLabel('Enabled').click();
  await page.locator('html').click();
  await page.getByPlaceholder('Search').click();
  await page.getByPlaceholder('Search').fill('');
  await page.getByRole('button', { name: 'Filter Clear filters' }).click();
  await page.getByText('Disabled').click();
  await page.getByLabel('Enabled').click();
  await page.locator('html').click();
  await page.getByLabel('Clear filters').click();
  await page.getByRole('link', { name: 'Dance style Enabled Dance' }).click();
  await page.getByText('Hip-Hop').click();
  await page.getByRole('row', { name: 'Hip-Hop Enabled' }).getByRole('switch').click();
  await page.getByRole('row', { name: 'Hip-Hop Enabled' }).getByRole('switch').click();
  await page.getByRole('row', { name: 'Hip-Hop Disabled' }).getByRole('img').first().click();
  await page.getByPlaceholder('Enter sub category name').click();
  await page.getByPlaceholder('Enter sub category name').fill('Hip-Hop1');
  await page.getByRole('button', { name: 'Edit name' }).click();
  await page.getByRole('button', { name: 'Add sub category' }).click();
  await page.getByPlaceholder('Enter sub category name').click();
  await page.getByPlaceholder('Enter sub category name').fill('Salsa');
  await page.getByRole('button', { name: 'Add sub category' }).click();
  await page.getByLabel('Add item').click();
  await page.getByRole('button', { name: 'Add sub category' }).click();
  await page.getByText('Salsa', { exact: true }).click();
  await page.getByPlaceholder('Enter sub category name').click();
  await page.getByPlaceholder('Enter sub category name').fill('SalsaNew');
  await page.getByPlaceholder('Enter sub category name').press('Enter');
  await page.locator('div').filter({ hasText: /^Salsa$/ }).getByRole('button').click();
  await page.getByRole('button', { name: 'Add sub category' }).click();
  await page.getByLabel('Go back').click();
});