import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://staging-fe.talenzap.com/competition');
  await page.getByRole('button', { name: 'Add Competition' }).click();
  await page.getByText('Select a cover image').click();
  await page.locator('body').setInputFiles('6mb.gif');
  await page.getByPlaceholder('Enter a title').click();
  await page.getByPlaceholder('Enter a title').fill('Beat Challenge');
  await page.getByPlaceholder('Enter a description').click();
  await page.getByPlaceholder('Enter a description').fill('Show off your moves and compete with amazing dancers from around the world.');
  await page.getByLabel('Category', { exact: true }).getByRole('combobox').click();
  await page.getByLabel('Dance styles').click();
  await page.getByLabel('Sub category').getByRole('combobox').click();
  await page.getByLabel('Street').getByText('Street').click();
  await page.getByLabel('Competition type').getByRole('combobox').click();
  await page.getByLabel('free').click();
  await page.getByPlaceholder('MM:SS').click();
  await page.getByPlaceholder('MM:SS').fill('02:55');
  await page.getByPlaceholder('Minimum participants').click();
  await page.getByPlaceholder('Minimum participants').fill('1');
  await page.getByPlaceholder('Minimum participants').click();
  await page.getByPlaceholder('Minimum participants').dblclick();
  await page.getByPlaceholder('Minimum participants').click();
  await page.getByPlaceholder('Minimum participants').click();
  await page.getByRole('main').locator('div').filter({ hasText: 'Enter a titleEnter a' }).nth(2).click();
  await page.getByPlaceholder('Minimum participants').click();
  await page.getByPlaceholder('Minimum participants').click({
    clickCount: 3
  });
  await page.getByPlaceholder('Minimum participants').dblclick();
  await page.getByPlaceholder('Maximum participants').click();
  await page.getByPlaceholder('Maximum participants').fill('100');
  await page.getByPlaceholder('Enter rules and regulations').click();
  await page.getByPlaceholder('Enter rules and regulations').fill('Timeline\nExecution\nprobs');
  await page.getByPlaceholder('Start date').click();
  await page.getByLabel('Today, Wednesday, January').click();
  await page.getByPlaceholder('Start time').click();
  await page.locator('button').filter({ hasText: '41' }).click();
  await page.getByLabel('57').click();
  await page.locator('button').filter({ hasText: '07' }).click();
  await page.getByLabel('08').click();
  await page.locator('button').filter({ hasText: '08' }).click();
  await page.getByText('11').click();
  await page.getByPlaceholder('Start date').click();
  await page.getByLabel('Thursday, January 29th,').click();
  await page.getByPlaceholder('Select competition start and').click();
  await page.getByLabel('Thursday, January 29th,').click();
  await page.locator('#radix-_r_9j_').getByPlaceholder('Start time').click();
  await page.locator('button').filter({ hasText: '07' }).click();
  await page.getByLabel('12', { exact: true }).getByText('12').click();
  await page.locator('#radix-_r_9j_').getByPlaceholder('End time').click();
  await page.locator('button').filter({ hasText: '07' }).click();
  await page.getByLabel('12', { exact: true }).getByText('12').click();
  await page.getByLabel('Friday, January 30th,').click();
  await page.getByRole('button', { name: 'Confirm' }).click();
  await page.getByPlaceholder('End date', { exact: true }).click();
  await page.getByLabel('Saturday, January 31st,').click();
  await page.getByPlaceholder('End time').click();
  await page.getByRole('spinbutton').nth(3).click();
  await page.getByRole('spinbutton').nth(3).click();
  await page.getByRole('spinbutton').nth(3).click();
  await page.getByRole('spinbutton').nth(3).fill('3');
  await page.getByRole('button', { name: 'Select goodies/items' }).click();
  await page.getByText('Samsung Galaxy S24 Ultra (').click();
  await page.getByRole('button', { name: 'Save as draft' }).click();
  await page.getByPlaceholder('Select competition start and').click();
  await page.locator('#radix-_r_9j_').getByPlaceholder('End time').click();
  await page.locator('#radix-_r_9j_').getByPlaceholder('End time').click();
  await page.locator('#radix-_r_9j_').getByPlaceholder('End time').click();
  await page.locator('div').filter({ hasText: /^Hour12$/ }).getByRole('combobox').click();
  await page.getByText('01', { exact: true }).click();
  await page.getByText('Select Start and End DateJanuary').click();
  await page.getByRole('button', { name: 'Confirm' }).click();
  await page.getByPlaceholder('End time').click();
  await page.locator('button').filter({ hasText: '07' }).click();
  await page.getByText('02').click();
  await page.getByRole('main').locator('div').filter({ hasText: 'Enter a titleEnter a' }).nth(1).click();
  await page.getByRole('button', { name: 'Publish competition' }).click();
  await page.getByPlaceholder('End date', { exact: true }).click();
  await page.getByLabel('Friday, January 30th,').click();
  await page.getByRole('button', { name: 'Publish competition' }).click();
  await page.getByPlaceholder('Start date').click();
  await page.getByLabel('Today, Wednesday, January').click();
  await page.getByRole('button', { name: 'Publish competition' }).click();
  await page.getByText('Save as draftPublish').click();
  await page.getByRole('button', { name: 'Save as draft' }).click();
});